### ISSUE TITLE
some fonts requests not redirected.

### ISSUE THREAD

**Issue by liudonghua123** [hans000/easy-interceptor#14]
Hi, I tried to use this extension to redirect some requests like `fonts.gstatic.com` to `gstatic.loli.net` and `fonts.googleapis.com` to `fonts.loli.net`.

So I added the following rule.

config:

```json
{
    "test": "fonts.gstatic.com",
    "groupId": "default",
    "response": {
        "code": 0,
        "data": [],
        "message": "success"
    }
}
```

code:

```js
onRedirect((rule) => {
    const redirectUrl = new URL(rule.url);
    redirectUrl.host = 'gstatic.loli.net';
    return redirectUrl.toString();
})
```

Some requests are redirected as expected.

![image](https://github.com/hans000/easy-interceptor/assets/2276718/2e8cc145-def0-4986-93f1-413c2f6584e0)

But some requests are not working.

![image](https://github.com/hans000/easy-interceptor/assets/2276718/5485783b-83ca-4272-a1f4-0c9a3f8be666)

**Comment by liudonghua123** [comment]
It seems the fonts request from inline style in index.html not handled via this extension.

```css
            @font-face {
                font-family: 'Material Icons';
                font-style: normal;
                font-weight: 400;
                src: url(https://fonts.gstatic.com/s/materialicons/v140/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2');
            }
```
